# Generated by Django 5.2.13 on 2026-04-11 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="algorithms",
            field=models.TextField(blank=True, help_text="One algorithm per line"),
        ),
        migrations.AddField(
            model_name="project",
            name="conclusion",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="project",
            name="dataset",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name="project",
            name="features",
            field=models.TextField(blank=True, help_text="One feature per line"),
        ),
        migrations.AddField(
            model_name="project",
            name="future_enhancements",
            field=models.TextField(blank=True, help_text="One enhancement per line"),
        ),
        migrations.AddField(
            model_name="project",
            name="objectives",
            field=models.TextField(blank=True, help_text="One objective per line"),
        ),
        migrations.AddField(
            model_name="project",
            name="problem_statement",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="category",
            field=models.CharField(
                choices=[
                    ("aiml", "AI & Machine Learning"),
                    ("java", "Java Full Stack"),
                    ("python", "Python Full Stack"),
                    ("mern", "MERN Stack"),
                    ("datascience", "Data Science"),
                ],
                default="aiml",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="tech_stack",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="project",
            name="thumbnail",
            field=models.ImageField(blank=True, null=True, upload_to="projects/"),
        ),
    ]
