services:
  - type: web
    name: vignantech
    region: singapore
    plan: free
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn vignan_tech.wsgi:application --bind 0.0.0.0:$PORT --workers 2 --threads 2 --timeout 120 --preload"
    envVars:
      - key: DATABASE_URL
        value: "postgresql://postgres.setyrsampeemjxcoeweo:Tsuresh%408055@aws-0-ap-south-1.pooler.supabase.com:6543/postgres"
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "vignantech.onrender.com,.onrender.com,localhost"
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: "3.10.0"
      - key: SENDGRID_API_KEY
        sync: false
      - key: DEFAULT_FROM_EMAIL
        value: "Vignan TechSolutions <vignantechsolutions@gmail.com>"
      - key: RAZORPAY_KEY_ID
        sync: false
      - key: RAZORPAY_KEY_SECRET
        sync: false
      - key: COMPANY_NAME
        value: "Vignan TechSolutions"
      - key: COMPANY_EMAIL
        value: "vignantechsolutions@gmail.com"
      - key: COMPANY_PHONE
        value: "+91-9110478047 / +91-9148215446"
      - key: COMPANY_ADDRESS
        value: "Kalaburagi, Karnataka, India"
