# Generated by Django 5.2.13 on 2026-04-09 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Internship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField()),
                ("duration", models.CharField(max_length=50)),
                ("fees", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "topics_covered",
                    models.TextField(help_text="Enter topics separated by newlines"),
                ),
                (
                    "benefits",
                    models.TextField(help_text="Enter benefits separated by newlines"),
                ),
                ("certificate_info", models.TextField()),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("online", "Online"),
                            ("offline", "Offline"),
                            ("hybrid", "Hybrid"),
                        ],
                        default="online",
                        max_length=10,
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(blank=True, null=True, upload_to="internships/"),
                ),
                ("seats_available", models.PositiveIntegerField(default=50)),
                ("is_featured", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
