# Generated by Django 5.2.13 on 2026-04-19 10:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("certificates", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomCertificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cert_number",
                    models.CharField(editable=False, max_length=30, unique=True),
                ),
                ("recipient_name", models.CharField(max_length=150)),
                (
                    "cert_type",
                    models.CharField(
                        choices=[
                            ("completion", "Certificate of Completion"),
                            ("internship", "Certificate of Internship"),
                            ("participation", "Certificate of Participation"),
                            ("excellence", "Certificate of Excellence"),
                            ("appreciation", "Certificate of Appreciation"),
                            ("training", "Certificate of Training"),
                        ],
                        default="completion",
                        max_length=20,
                    ),
                ),
                (
                    "program_name",
                    models.CharField(
                        help_text="Course / Internship / Program name", max_length=200
                    ),
                ),
                (
                    "duration",
                    models.CharField(
                        blank=True, help_text="e.g. 4 Weeks, 3 Months", max_length=100
                    ),
                ),
                ("issued_date", models.DateField()),
                (
                    "issued_by",
                    models.CharField(default="Vignan TechSolutions", max_length=150),
                ),
                (
                    "signatory_name",
                    models.CharField(default="Director", max_length=100),
                ),
                (
                    "signatory_title",
                    models.CharField(default="Vignan TechSolutions", max_length=100),
                ),
                (
                    "extra_note",
                    models.CharField(
                        blank=True,
                        help_text="Optional line below program name",
                        max_length=300,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="custom_certificates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Custom Certificate",
                "verbose_name_plural": "Custom Certificates",
                "ordering": ["-created_at"],
            },
        ),
    ]
