# Generated by Django 5.2.13 on 2026-04-19 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("certificates", "0002_customcertificate"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customcertificate",
            name="duration",
        ),
        migrations.RemoveField(
            model_name="customcertificate",
            name="issued_by",
        ),
        migrations.AddField(
            model_name="customcertificate",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customcertificate",
            name="project_domain",
            field=models.CharField(
                blank=True,
                help_text="e.g. Artificial Intelligence / Machine Learning / Data Science",
                max_length=300,
            ),
        ),
        migrations.AddField(
            model_name="customcertificate",
            name="signatory_org",
            field=models.CharField(default="Vignan Tech Solutions", max_length=100),
        ),
        migrations.AddField(
            model_name="customcertificate",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="customcertificate",
            name="cert_type",
            field=models.CharField(
                choices=[
                    ("completion", "Project Completion"),
                    ("internship", "Internship"),
                    ("participation", "Participation"),
                    ("excellence", "Excellence"),
                    ("appreciation", "Appreciation"),
                    ("training", "Training"),
                ],
                default="completion",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="customcertificate",
            name="extra_note",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name="customcertificate",
            name="program_name",
            field=models.CharField(
                help_text="Project / Course / Program title", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="customcertificate",
            name="signatory_name",
            field=models.CharField(default="Suresh Tammali", max_length=100),
        ),
        migrations.AlterField(
            model_name="customcertificate",
            name="signatory_title",
            field=models.CharField(default="Director", max_length=100),
        ),
    ]
