# Generated by Django 5.2.13 on 2026-04-11 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="testimonial",
            name="is_approved",
            field=models.BooleanField(
                default=False, help_text="Approve to show on website"
            ),
        ),
    ]
